name: stpl
description: A language for describing training programs.
version: 1.0.0
repository: https://github.com/danilopedraza/stpl

environment:
  sdk: ^3.0.5

dependencies:
  collection: ^1.18.0

dev_dependencies:
  lints: ^2.0.0
  mockito: ^5.4.2
  test: ^1.21.0
